[project]
name = "open-nvim-with-wezterm"
version = "0.1.0"
description = "This small project opens Neovim in WezTerm terminal"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.14.2",
]
